### ISSUE TITLE
Size has no affect in 3.0.0

### ISSUE THREAD

**Issue by theDanielJLewis** [mmkari/react-star-picker#58]
I noticed the deprecation of `numberStars` in favor of `starCount` (but the documentation hasn't been updated, yet). However, it appears that `size` no longer works and it doesn't look deprecated.

I previously had `size={40}`, and after updating to 3.0.0, the stars are small and changing the size number doesn't help me.

Nonetheless, the workaround I'm moving forward with is to use Tailwind's text-sizing classes. In my specific case, I'm using `text-[40px]/[40px]` (overriding the line-height is necessary in my use).

**Comment by mmkari** [comment]
Hi @theDanielJLewis, did you get a chance to test the above? Closing this issue in one week if no word 🙂

**Comment by mmkari** [comment]
Thanks for the confirmation 🙏
